config/routes.rb
Rails.application.routes.draw do
  resources :photos
  root "photos#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file_location, PhotoImageUploader
  #validates_presence_of :title, :date, :description, :file_location
  validates :title, :date, :description, :file_location,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render :new
    end

  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update(photo_params)

    redirect_to photo_path(@photo)
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to photos_path

  end


  private

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoAlbum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo  do |f|%>
<div class="form-group">
<!--  <% if @photo.errors.present?  %>
      <ul>
        <% @photo.errors.each do |error, message| %>
            <li>  <%= "#{error.capitalize} #{message}" %></li>
        <% end %>
      </ul>
  <% end %> -->
    <% if @photo.errors.any? %>
      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
            <li>  <%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
    <br>
    <br>
    <%= f.label :date, "Date" %>
    <%= f.text_field :date %>
    <br>
    <br>
    <%= f.label :description, "Description" %>
    <%= f.text_field :description %>
    <br>
    <br>
    <%= f.label :file_location, "file_location" %>
    <%= f.file_field :file_location %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

</div>

app/views/photos/edit.html.erb
<h2>  編輯頁面！</h2>
<%= render :partial => "form" %>

app/views/photos/index.html.erb
<ul>
  <% @photos.each do |photo| %>
    <li>
      <%= photo.title %>
      
      <%= link_to "Show", photo_path(photo) %>
      <%= link_to("Edit",edit_photo_path(photo)) %>
      <%= link_to("Destroy", photo_path(photo), method: :delete, data:{ confirm: "Are you sure?"}) %>
    </li>
  <% end %>
</ul>

<%= link_to("New Photo", new_photo_path) %>

app/views/photos/new.html.erb
<h2>  New photo</h2>
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<%= @photo.title %>
<br>
<%= @photo.date %>
<br>  <br>  <br>
<%= image_tag @photo.file_location.url %>
<%= simple_format(@photo.description) %>

<p>  <%= link_to("Back to index", photos_path) %></p>